//! Black-box integration suite for `services/api`, run against the REAL
//! compiled binary (not an in-process `Router`) over a committed fixture
//! snapshot (`tests/fixtures/`, generated by
//! `services/workers/examples/gen_api_test_fixture.rs` — see that file for
//! the 7 hand-crafted events this suite's assertions are built around).
//! Spawning the actual binary exercises real TCP/HTTP and the middleware
//! stack end to end, matching this project's standing verification
//! discipline (HANDOFF.md: "verify against a RUNNING api, not by reading
//! code") in a form CI can run unattended.

use std::process::{Child, Command, Stdio};
use std::time::Duration;

use serde_json::Value;

/// Kills the spawned api process on drop, so a failing assertion (which
/// unwinds past the normal end of the test function) doesn't leak it.
struct ApiProcess(Child);

impl Drop for ApiProcess {
    fn drop(&mut self) {
        let _ = self.0.kill();
        let _ = self.0.wait();
    }
}

fn fixtures_dir() -> String {
    format!("{}/tests/fixtures", env!("CARGO_MANIFEST_DIR"))
}

async fn spawn_and_wait_ready(
    client: &reqwest::Client,
    bind: &str,
    extra_env: &[(&str, &str)],
) -> ApiProcess {
    let base = format!("http://{bind}");
    let mut cmd = Command::new(env!("CARGO_BIN_EXE_api"));
    cmd.env("LES_PUBLISH_DIR", fixtures_dir())
        .env("LES_API_BIND", bind)
        .env("RUST_LOG", "error")
        .stdout(Stdio::null())
        .stderr(Stdio::null());
    for (k, v) in extra_env {
        cmd.env(k, v);
    }
    let child = cmd
        .spawn()
        .expect("spawn the api binary (cargo test builds it first via CARGO_BIN_EXE_api)");
    let proc = ApiProcess(child);

    for _ in 0..50 {
        if let Ok(resp) = client.get(format!("{base}/health")).send().await
            && resp.status().is_success()
        {
            return proc;
        }
        tokio::time::sleep(Duration::from_millis(100)).await;
    }
    panic!("api on {bind} did not become ready within 5s");
}

async fn json_body(resp: reqwest::Response) -> Value {
    let status = resp.status();
    let text = resp.text().await.expect("response body readable");
    serde_json::from_str(&text).unwrap_or_else(|e| panic!("status {status}, body {text:?}: {e}"))
}

/// Covers /health, /meta, /buckets, /events (pagination + the precision
/// filter), /metrics, /openapi.json, ETag/If-None-Match, and a best-effort
/// per-IP rate-limit check — everything that doesn't need
/// `LES_API_ALLOW_ACLED` toggled (see `events_include_acled_rows_when_opted_in`
/// for that).
#[tokio::test]
async fn full_api_surface_over_the_fixture_snapshot() {
    const BIND: &str = "127.0.0.1:18199";
    const BASE: &str = "http://127.0.0.1:18199";
    let client = reqwest::Client::new();
    let _proc = spawn_and_wait_ready(&client, BIND, &[]).await;

    // /health: snapshot present; staleness fields exist as data, not
    // asserted for a specific value — this committed fixture's
    // `published_at_epoch_s` is frozen at generation time, so `stale` will
    // legitimately flip to `true` as it ages. The threshold logic itself is
    // covered by `snapshot_staleness`'s unit tests in `src/main.rs`.
    let health = json_body(client.get(format!("{BASE}/health")).send().await.unwrap()).await;
    assert_eq!(health["status"], "ok");
    assert_eq!(health["snapshot"]["events"], 7);
    assert_eq!(health["snapshot"]["buckets"], 6);
    assert!(health["snapshot_age_s"].as_i64().is_some_and(|s| s >= 0));
    assert!(health["stale"].is_boolean());

    // /meta
    let meta = json_body(client.get(format!("{BASE}/meta")).send().await.unwrap()).await;
    assert!(!meta["time_extent"].is_null());
    let synthetic_count = meta["themes"]
        .as_array()
        .unwrap()
        .iter()
        .find(|t| t["theme"] == "synthetic")
        .expect("every fixture event carries the synthetic theme")["count"]
        .as_u64()
        .unwrap();
    assert_eq!(synthetic_count, 7);

    // /buckets: full window, all 6 published buckets; end <= start is 400.
    let buckets_resp = client
        .get(format!("{BASE}/buckets?start=1781827200&end=1782172800"))
        .send()
        .await
        .unwrap();
    assert_eq!(buckets_resp.status(), 200);
    let buckets = json_body(buckets_resp).await;
    assert_eq!(buckets.as_array().unwrap().len(), 6);

    let bad_window = client
        .get(format!("{BASE}/buckets?start=100&end=100"))
        .send()
        .await
        .unwrap();
    assert_eq!(bad_window.status(), 400);

    // /events: only the 3 GDELT city-precision rows by default — the 2
    // ACLED city rows are excluded (LES_API_ALLOW_ACLED unset), the ACLED
    // admin1 row and the GDELT country row are excluded by the precision
    // filter regardless of source.
    let events = json_body(
        client
            .get(format!("{BASE}/events?start=1781827200&end=1782172800"))
            .send()
            .await
            .unwrap(),
    )
    .await;
    assert_eq!(events["total"], 3);
    assert_eq!(events["rows"].as_array().unwrap().len(), 3);

    // Pagination: (ts_epoch_s DESC, id DESC) — Jakarta (06-22) first, then
    // Nairobi (06-21), then Paris (06-20). `total` stays 3 on every page.
    let page1 = json_body(
        client
            .get(format!(
                "{BASE}/events?start=1781827200&end=1782172800&limit=2&offset=0"
            ))
            .send()
            .await
            .unwrap(),
    )
    .await;
    let page1_rows = page1["rows"].as_array().unwrap();
    assert_eq!(page1["total"], 3);
    assert_eq!(page1_rows.len(), 2);
    assert!(
        page1_rows[0]["headline"]
            .as_str()
            .unwrap()
            .contains("Jakarta")
    );
    assert!(
        page1_rows[1]["headline"]
            .as_str()
            .unwrap()
            .contains("Nairobi")
    );

    let page2 = json_body(
        client
            .get(format!(
                "{BASE}/events?start=1781827200&end=1782172800&limit=2&offset=2"
            ))
            .send()
            .await
            .unwrap(),
    )
    .await;
    let page2_rows = page2["rows"].as_array().unwrap();
    assert_eq!(page2["total"], 3);
    assert_eq!(page2_rows.len(), 1);
    assert!(
        page2_rows[0]["headline"]
            .as_str()
            .unwrap()
            .contains("Paris")
    );

    let bad_events_window = client
        .get(format!("{BASE}/events?start=100&end=100"))
        .send()
        .await
        .unwrap();
    assert_eq!(bad_events_window.status(), 400);

    // /metrics: Prometheus text, reflecting the requests already made above.
    let metrics_text = client
        .get(format!("{BASE}/metrics"))
        .send()
        .await
        .unwrap()
        .text()
        .await
        .unwrap();
    assert!(metrics_text.contains("http_requests_total"));
    assert!(metrics_text.contains("http_request_duration_seconds"));

    // /openapi.json: valid JSON, describes the real routes.
    let openapi = json_body(
        client
            .get(format!("{BASE}/openapi.json"))
            .send()
            .await
            .unwrap(),
    )
    .await;
    assert!(openapi["paths"]["/events"].is_object());
    assert!(openapi["paths"]["/health"].is_object());

    // ETag / If-None-Match: a repeat request with the prior ETag gets 304.
    let first = client.get(format!("{BASE}/health")).send().await.unwrap();
    let etag = first
        .headers()
        .get(reqwest::header::ETAG)
        .expect("ETag header present")
        .to_str()
        .unwrap()
        .to_string();
    let conditional = client
        .get(format!("{BASE}/health"))
        .header(reqwest::header::IF_NONE_MATCH, &etag)
        .send()
        .await
        .unwrap();
    assert_eq!(conditional.status(), 304);

    // Per-IP rate limit: RATE_LIMIT_BURST=20, so a burst of 40 concurrent
    // requests from this one client should see at least one 429. Best-effort
    // (real-time token bucket) rather than an exact count.
    let mut handles = Vec::new();
    for _ in 0..40 {
        let client = client.clone();
        handles.push(tokio::spawn(async move {
            client
                .get(format!("{BASE}/meta"))
                .send()
                .await
                .map(|r| r.status())
        }));
    }
    let mut saw_429 = false;
    for h in handles {
        if let Ok(Ok(status)) = h.await
            && status == 429
        {
            saw_429 = true;
        }
    }
    assert!(
        saw_429,
        "expected at least one 429 from a 40-request burst against a burst-20 limiter"
    );
}

/// `LES_API_ALLOW_ACLED=1` is the private-deployment escape hatch
/// (docs/API.md) — with it set, the 2 ACLED city rows join the 3 GDELT
/// city rows in `/events`. A separate process/port so this doesn't race
/// the default-policy assertions above.
#[tokio::test]
async fn events_include_acled_rows_when_opted_in() {
    const BIND: &str = "127.0.0.1:18200";
    const BASE: &str = "http://127.0.0.1:18200";
    let client = reqwest::Client::new();
    let _proc = spawn_and_wait_ready(&client, BIND, &[("LES_API_ALLOW_ACLED", "1")]).await;

    let events = json_body(
        client
            .get(format!("{BASE}/events?start=1781827200&end=1782172800"))
            .send()
            .await
            .unwrap(),
    )
    .await;
    assert_eq!(events["total"], 5);
}
